### ISSUE TITLE
minor error in abortion_dd.R

### ISSUE THREAD

**Issue by ianschmutte** [scunning1975/mixtape#11]
Love these materials. I was just working through them and noticed that in `abortion_dd.R` I needed to change lines 28 and 29 to 

```
sd = reg$std.error[-1:-25],
mean = reg$coefficients[-1:-25],
```
Currently, they run `[-1:-75]`

**Comment by scunning1975** [comment]
Fixed this. Thanks Ian.

**Comment by erauld** [comment]
Agree, excelent material. Thanks Scott. 

In my case the previous version worked fine. In fact, to make the tibble the coeffs and sd needed are `[-1:-75]`:

 Am I right?
