### ISSUE TITLE
Issues with lmb_5.R and lmb_6.R

### ISSUE THREAD

**Issue by kylebutts** [scunning1975/mixtape#12]
`lmb_data %>% 
  mutate(demvoteshare_sq = demvoteshare_c^2)`

need 
`lmb_data <- lmb_data %>% 
  mutate(demvoteshare_sq = demvoteshare_c^2)
`

**Comment by stnavdeev** [comment]
To be able to replicate the results and have 2441 observations, it has to be:
lmb_subset <- lmb_subset %>% 
  filter(lagdemvoteshare > .45 & lagdemvoteshare < .55)
