### ISSUE TITLE
Set notation in Probability and Regression Review

### ISSUE THREAD

**Issue by MokeEire** [scunning1975/mixtape#15]
I am not sure if this is the right place to mention issues with the book's content itself.  If not, feel free to close!

In the [Probability Tree section](https://mixtape.scunning.com/ch1.html#probability-tree), the footnote is not displaying the latex equation correctly (and I believe _union_ should be _intersection_):

> The set notation \\(\\cap\\)</span> means “union” and refers to two events occurring together.

This seems to occur inside other footnotes too.

Similarly, in the [Venn Diagram and Sets section](https://mixtape.scunning.com/ch1.html#venn-diagrams-and-sets) (errors in bold):

> Whenever we want to describe a set of events in which either A or B could occur, **it is: A∩B.** And this is pronounced “A union B,” which means it is the new set that contains every element from A and every element from B. Any element that is in either set A or set B, then, is also in the new union set. And whenever we want to describe a set of events that occurred together—the joint set—**it’s A∪B**, which is pronounced “A intersect B.”

In the [Contingency Tables section](https://mixtape.scunning.com/ch1.html#contingency-tables), in table 2.4 the table headers describing events B and ~B are mixed up:  

Event labels | **_Coach is not rehired (B)_** | **_Coach is rehired (∼B)_** | Total
-- | -- | -- | --
(A)(A) Bowl game | Pr(A,∼B)Pr(A,∼B)=0.1 | Pr(A,B)Pr(A,B)=0.5 | Pr(A)Pr(A)=0.6
(∼A)(∼A) no Bowl game | Pr(∼A,∼B)=0.1Pr(∼A,∼B)=0.1 | Pr(∼A,B)=0.3Pr(∼A,B)=0.3 | Pr(B)=0.4Pr(B)=0.4
Total | Pr(∼B)=0.2Pr(∼B)=0.2 | Pr(B)=0.8Pr(B)=0.8 | 1.0

Below equation 2.7 in the same section, the term Pr(A,B) is missing an ending bracket, and equation 2.8 is not tagged correctly.
Hope this is somewhat helpful!

**Comment by kylebutts** [comment]
Thank you for the corrections! Much appreciated

**Comment by MokeEire** [comment]
Oh also the ~A row total of the contingency table should show ~A rather than B.
