### ISSUE TITLE
Typo in reference to figure

### ISSUE THREAD

**Issue by ahdvnd** [scunning1975/mixtape#23]
On [this page](https://mixtape.scunning.com/instrumental-variables.html#the-problem-of-weak-instruments), there is a reference to figure 49 whereas all other figures are references as Figure 7.x. Here's the paragraph:

"Figure 49 shows the first stage, and it is really interesting. Look at all those 3s and 4s at the top of the picture. There’s a clear pattern—those with birthdays in the third and fourth quarter have more schooling on average than do those with birthdays in the first and second quarters. That relationship gets weaker as we move into later cohorts, but that is probably because for later cohorts, the price on higher levels of schooling was rising so much that fewer and fewer people were dropping out before finishing their high school degree."

**Comment by kylebutts** [comment]
Thank you!
