### ISSUE TITLE
is ssl tweak needed for some extra protection?

### ISSUE THREAD

**Issue by epogrebnyak** [scunning1975/mixtape#24]
@kylebutts, great jon on python version! Curious about ssl import:

https://github.com/scunning1975/mixtape/blob/a8d007b0fa24a1b143b8401a29695ab7958ded9f/python/card.py#L9-L10

Would python code work without it?

**Comment by epogrebnyak** [comment]
It looks `pd.read_stata` may work without `ssl` tweak:

```python 
import pandas as pd

df = pd.read_stata("https://raw.github.com/scunning1975/mixtape/master/card.dta")
```
https://colab.research.google.com/drive/1uKDeW7N0X-Z3eAmGdBU1gaF5HIvl6RJI?usp=sharing

If ssl config this is a border case - maybe put a note about it in the text or the first case, but do not include in every example?
It distracts attention from the modelling a bit.

**Comment by kylebutts** [comment]
it's quite possible that I have installed python poorly but `pd.read_stata` doesn't work without the ssl tweak for me. I have no sense of how common that issue is, so I'm not sure if I should
