### ISSUE TITLE
Typo in book - Probability and Regression Review, page 71, equation 2.44

### ISSUE THREAD

**Issue by Roobite** [scunning1975/mixtape#31]
> Now, under the first, fourth, and fifth, assumptions, we can write:
> ...
> V(y|x) = σ^2

Should be V(u|x) = σ^2?

**Comment by kylebutts** [comment]
I think both are equivalent actually! $E(y \vert x) = x\beta$, so $Var(y \vert x) = Var(u \vert x)$
