### ISSUE TITLE
stargazer not imported in this file prior to use 

### ISSUE THREAD

**Issue by joehcollins** [scunning1975/mixtape#33]
Just to let you know that stargazer is not imported in this file so the code will error at this line:
https://github.com/scunning1975/mixtape/blob/77e3de4628e6cac5211281c4abe0d964d888be2c/python/collider_discrimination.py#L30

Seems fine in the other file in this chapter (chapter 3) which is movie_star.py.

(Really enjoying the book so far!! Thanks so much)

**Comment by kylebutts** [comment]
Thanks! We are updating the python files a lot right now, so this should be fixed :-)
