### ISSUE TITLE
Typo in Figure 10.8 title

### ISSUE THREAD

**Issue by alexanderthclark** [scunning1975/mixtape#35]
In [Chapter 10](https://mixtape.scunning.com/synthetic-control.html#prison-construction-and-black-male-incarceration), there is a typo in figure 10.8. 

The plot title says "Back male incarceration" instead of "Black male incarceration." Doesn't look like the code for that figure is included, so I'm not sure where to find the typo and make a pull request.

**Comment by kylebutts** [comment]
Thanks Alexander! I'll fix that now

**Comment by kylebutts** [comment]
Actually @scunning1975, we will need to figure this out b/c I can't edit the figure images on my end.
