### ISSUE TITLE
Chapter 9, code castle_5 not included on the website, 1 minor typo

### ISSUE THREAD

**Issue by loikein** [scunning1975/mixtape#41]
Dear Scott, thank you for this extremely valuable and easy-to-read book. Recently I was given chapter 9 of it as reading, and found two issues that I thought I could tell you here.

1\. Missing `castle_5` on the website

Link: [9. Difference-in-Differences 9.6.8 Bacon decomposition](https://mixtape.scunning.com/09-difference_in_differences#bacon-decomposition).

On pp.499-500 of the book there are `castle_5.do` and `castle_5.r`, and they are also in this repository, plus the Python version.

2\. Typo in both the book and the website

Link: [9  Difference-in-Differences 9.5.7 Final thoughts](https://mixtape.scunning.com/09-difference_in_differences#final-thoughts), and also p.461 of the paper book (sorry I don't know if I have the latest edition, but since it's also on the website, I assume it was not spotted yet.)

> These, it turns, out are

Should be: These, it turns out, are

**Comment by kylebutts** [comment]
Hi @loikein; thanks for flagging these! They have been addressed and the website is updating now.
