### ISSUE TITLE
"Noncollider" used before colliders is defined

### ISSUE THREAD

**Issue by jdonland** [scunning1975/mixtape#42]
In section 3.1.1 of the version of _Causal Inference: The Mixtape_ available [here](https://mixtape.scunning.com/), in the first paragraph after the second figure, the term "noncollider" is used before colliders have been defined.

**Comment by kylebutts** [comment]
Hi Jesse, 

Thanks for flagging this. Scott is in the process of a second revised edition of the book, so I'm sure he appreciate this.
