### ISSUE TITLE
Broken navigation footer

### ISSUE THREAD

**Issue by jdonland** [scunning1975/mixtape#43]
In the version of _Causal Inference: The Mixtape_ available [here](https://mixtape.scunning.com/), the navigation footer displays what appears to be part of an HTML tag as visible text. (Encountered in Firefox 129.0.2 on Windows 10.)

![image](https://github.com/user-attachments/assets/7ad9c9a1-884d-4251-b38e-13c55899cb5a)

**Comment by kylebutts** [comment]
Thanks, fixed!
