### ISSUE TITLE
Castle.R issues

### ISSUE THREAD

**Issue by be-green** [scunning1975/mixtape#6]
@ttp63 was kind enough to notice some issues with the two-way fixed effects model in castle, but it seems that there are some issues with the new version:

- Colinearity raises a warning because of a singular matrix in both regressions in castle_1.R
- Inclusion of original Cheng and Hoekstra specification with CDL as the causal regressor doesn't line up with castle_1.do

**Comment by ttp63** [comment]
Hi @be-green , thanks for pointing these out. 
- Is the colinearity warning a problem that needs to be fixed? I think the stata program gives the same warning and produces the same output as the R program, so I figured it wasn't a big deal. 
- Also I don't think that the castle_1.do file includes an extra regression with CDL as the causal regressor, it only uses post as a regressor. So maybe we don't need the CDL regression in the R program at all? Or maybe we should add a CDL regression to the stata program?

**Comment by be-green** [comment]
Yeah--I investigated the colinearity bit. It looks like it has to do with a Wald test run in the `summary.felm` code that the lfe package uses. LFE is automatically dropping colinear regressors at that stage, it's just being quiet about it so there's not an issue. And yeah, I just took out the extra formula. Looks like it's all matching up now.
